name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # - name: Black
      #   run: black --check src tests

      - name: Isort
        run: isort --check-only src tests

      # - name: Flake8
      #   run: flake8 src tests

      - name: Pytest
        run: pytest tests/test_quickstart.py
